on:
  release:
    types: [created]

name: Deploy to VPS

jobs:
  build:
    name: Build
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: composer install
        run: docker exec -i erp sh -c "composer install -n"
        
      - name: build erp-prod
        run: |
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        docker build -t jackyhtg/erp-prod:$VERSION .
        
  deploy:
    needs: build
    
    name: Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
        
      - name: push docker and ssh to myVPS
        run: |
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        docker push jackyhtg/erp-prod:$VERSION
        ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} /root/erp-prod $VERSION
